name: Deploy

on: 
  push:
    branches: 
      - "release"
  pull_request:
    branches: 
      - "release"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup .NET Core 2.2
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.402

    - name: Install DocFX
      run: |
        dotnet tool install docfx --tool-path "docs" --version "3.0.0-*" --add-source https://www.myget.org/F/docfx-v3/api/v2

    - name: Generate static documentation with DocFX
      run: |
        cd docs
        ls
        ./docfx restore
        ./docfx build
        echo -----
        ls docs/api
        echo -----
        ls docs/_site

    - name: Deploy documentation to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: release
        BRANCH: gh-pages
        FOLDER: docs/_site
