name: Deploy

on:
  push:
    branches:
      - "release"

jobs:
  deploy_package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core 3.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100

    - name: Create NuGet package
      run: dotnet pack src/Apod/Apod.csproj -c Release --output nupkgs

    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: 'latest'
    
    - name: Publish package to NuGet.org
      run: nuget push nupkgs/*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate
    
    - name: Publish package to the Github Package Registry
      run: |
        nuget setApiKey ${{ secrets.NUGET_API_KEY }}
        nuget sources Add -Name "GPR" -Source "https://nuget.pkg.github.com/lemorrow/index.json" -UserName LeMorrow -Password ${{ secrets.GITHUB_TOKEN }}
        nuget push nupkgs/*.nupkg -Source "GPR" -SkipDuplicate

  # Generates the documentation with DocFX and uploads the static website as an artifact
  generate_docs:
    runs-on: windows-latest # On windows because DocFX was difficult to install on other machines
    
    steps:
    - uses: actions/checkout@v1
    
    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: 'latest'
      
    - name: Install DocFX
      run: nuget install docfx.console -Version 2.47.0
    
    - name: Generate site with DocFX
      run: |
       docfx.console.2.47.0\tools\docfx.exe metadata docs/docfx.json
       docfx.console.2.47.0\tools\docfx.exe build docs/docfx.json
      
    - name: Upload site artifact
      uses: actions/upload-artifact@v1
      with:
        name: site
        path: docs/_site
  
  # Publishes the documentation website to the gh-pages branch
  deploy_docs:
    needs: generate_docs
    runs-on: ubuntu-latest 

    steps:
    
    - name: Download site artifact
      uses: actions/download-artifact@v1
      with:
        name: site
    
    - name: Deploy site to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: release
        BRANCH: gh-pages
        FOLDER: site
